[phases.setup]
nixPkgs = ["python310", "postgresql"]
nixOverlays = ["https://github.com/railwayapp/nix-verticals/archive/main.tar.gz"]
nixpkgsArchive = "bc8f8d1be58e8c8383e683a06e1e1e57893fff87"

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python -m compileall ."]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - run:app"
